version: '3'
services:

    oracle:
        image: container-registry.oracle.com/database/express:latest
        container_name: oracle
        restart: always
        ports:
            - "1521:1521"  # please make sure no Oracle instance is running on 1521
            - "5500:5500"
        environment:
            ORACLE_PWD: oracle

        volumes:
            - "oradata:/opt/oracle/oradata"

volumes:
    oradata: